name: citkid
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - scipy
  - pandas
  - jupyterlab
  - tqdm
  - numpy
  - matplotlib
  - python
  - pyfftw
  - numba
  - ipywidgets
  - ipympl
  - pip
  - emcee
  - corner
  - pip:
    - -e .
