name: citkid
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - scipy=1.16.3
  - pandas=2.3.3
  - jupyterlab=4.5.0
  - tqdm=4.67.1
  - numpy=2.3.5
  - matplotlib=3.10.8
  - python=3.12
  - pyfftw=0.15.1
  - numba=0.62.1
  - ipywidgets=8.1.8
  - ipympl=0.9.8
  - pip=25.3
  - emcee=3.1.6
  - corner=2.2.3
  - paramiko=4.0.0
  - redis=3.5.3
  - pip=25.3:
  - pip:
    - -e .
  - pytest=9.0.1
  - zarr=2.18.6
