import pytest 
import citkid.pipeline.dependencies as rv 

# For all of this, I am not testing the structure of the saved dict. 
# I am assuming that it is produced by other parts of the code correctly.

################################################################################
############################### _get_most_recent_run ###########################
################################################################################
@pytest.mark.parametrize("name,deps_map,expected", [
    # Basic case: parameter exists in multiple runs
    ("param1", {0: {"param1": {}, "param2": {}},
                1: {"param3": {}},
                2: {"param1": {}, "param4": {}}}, 2),
    # Parameter exists only in one run
    ("param2", {0: {"param1": {}},
                1: {"param2": {}}}, 1),
    # Parameter does not exist in any run
    ("paramX", {0: {"param1": {}},
                1: {"param2": {}}}, -1),
    # Empty deps_map dictionary
    ("param1", {}, -1),
    # skipped runs
    ("param1", {0: {"param2": {}},
                2: {"param1": {}}}, 2),
])
def test_get_most_recent_run(name, deps_map, expected):
    result = rv.get_most_recent_run(name, deps_map)
    assert result == expected


@pytest.mark.parametrize("name,deps_map", [
    (123, {0: {"param1": {}}}),  # name is not a string
    ("param1", [("param1", {})]),   # deps_map is not a dict   
])
def test_get_most_recent_run_invalid_inputs(name, deps_map):
    with pytest.raises(ValueError):
        rv.get_most_recent_run(name, deps_map)

def test_get_most_recent_run_ignores_non_dict_run_entries():
    # Run 0 is a non-dict (legacy/invalid), run 1 is proper dict
    deps_map = {0: [("param1", {})], 1: {"param1": {}}}
    assert rv.get_most_recent_run("param1", deps_map) == 1

################################################################################
################################# _get_sub_deps ################################
################################################################################
@pytest.mark.parametrize("name,run_idx,deps_map,expected", [
    # Basic case: parameter exists with deps
    ("param1", 2, {2: {"param1": {"param2": 1, "param3": 0}}}, 
                   {"param2": 1, "param3": 0}),
    # Parameter exists with no deps
    ("param2", 1, {1: {"param2": {}}}, {}),
    # Parameter does not exist in the specified run
    ("paramX", 0, {0: {"param1": {}}}, LookupError),
    # Invalid deps type for a parameter
    ("param1", 2, {2: {"param1": []}}, 
                   ValueError),
    # Empty deps
    ("param3", 3, {3: {"param3": {}}}, {}),
    # skipped runs
    ("param1", 2, {0: {"param1": {}},
                   2: {"param2": {}}}, LookupError),
    # Parameter exists in earlier run but not in specified run
    ("param1", 1, {0: {"param1": {}}, 
                   1: {"param2": {}}}, LookupError),
])
def test_get_sub_deps(name, run_idx, deps_map, expected):
    if expected is LookupError:
        with pytest.raises(LookupError):
            rv._get_sub_deps(name, run_idx, deps_map)
    elif expected is ValueError:
        with pytest.raises(ValueError):
            rv._get_sub_deps(name, run_idx, deps_map)
    else:
        result = rv._get_sub_deps(name, run_idx, deps_map)
        assert result == expected


@pytest.mark.parametrize("name,run_idx,deps_map", [
    (123, 0, {0: {"param1": {}}}),  # name is not a string
    ("param1", "0", {0: {"param1": {}}}),  # run_idx is not an integer
    ("param1", 0, [("param1", {})]),   # deps_map is not a dict   
])
def test_get_sub_deps_invalid_inputs(name, run_idx, deps_map):
    with pytest.raises(ValueError):
        rv._get_sub_deps(name, run_idx, deps_map)

def test_get_sub_deps_missing_run():
    deps_map = {0: {"param1": {}}}
    with pytest.raises(LookupError):
        rv._get_sub_deps("param1", 1, deps_map)

################################################################################
############################### _get_lowest_runs ###############################
################################################################################
# Not validating structure of sub_deps beyond being a dict, because 
# it is generated by _get_sub_deps which is already tested.
@pytest.mark.parametrize("sub_deps,sd_exp,conflicts_exp", [
    # Basic case: multiple parameters with different runs
    ({"param1": {"paramA": 2, "paramB": 3},
      "param2": {"paramA": 1, "paramC": 4}}, 
     {"paramA": 1, "paramB": 3, "paramC": 4}, True),
    # Single parameter with single dependency
    ({"param1": {"paramA": 5}}, 
     {"paramA": 5}, False),
    # Multiple parameters with overlapping deps
    ({"param1": {"paramA": 3, "paramB": 2},
      "param2": {"paramA": 1, "paramB": 4}}, 
     {"paramA": 1, "paramB": 2}, True),
    # Empty sub_deps
    ({}, {}, False),
    # Parameters with no deps
    ({"param1": {}, "param2": {}}, {}, False),
])
def test_get_lowest_runs(sub_deps, sd_exp, conflicts_exp):
    result, conflicts = rv._get_lowest_runs(sub_deps)
    assert result == sd_exp
    assert conflicts == conflicts_exp

@pytest.mark.parametrize("sub_deps", [
    ["param1", {"paramA": 2}],  # sub_deps is not a dict
])
def test_get_lowest_runs_invalid_inputs(sub_deps):
    with pytest.raises(ValueError):
        rv._get_lowest_runs(sub_deps)

def test_get_lowest_runs_invalid_subdep_value():
    with pytest.raises(ValueError):
        rv._get_lowest_runs({"param1": [1, 2]})

def test_get_deps_three_level_cascade():
    """Test cascading dependencies: a1 → b1 → c1 where all are inputs."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'b1': 1, 'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'b1': 1, 'a1': 1, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0},
            'c1': {'b1': 2, 'a1': 2, 'directory': 0}}
    }
    
    # Request all three at their highest runs - should backtrack a1 and b1 to run 1
    # c1 can stay at run 2 since it's compatible with the backtracked versions
    with pytest.warns(UserWarning):
        result = rv.get_deps(['a1', 'b1', 'c1'], deps_map)
        expected = {'a1': 1, 'b1': 1, 'c1': 2, 'directory': 0}
        assert result == expected

################################################################################
################################### get_deps ###################################
################################################################################
def test_get_deps_multiple_independent_params():
    """Test requesting multiple independent parameters at most recent run."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'a2': {'directory': 0},
            'c1': {'a1': 1, 'directory': 0},
            'c2': {'a2': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'a2': {'directory': 0},
            'c1': {'a1': 2, 'directory': 0},  # c1 updated to use a1:2
            'c2': {'a2': 2, 'directory': 0},  # c2 updated to use a2:2
            'b1': {'a1': 2, 'c1': 2, 'directory': 0},  # includes all transitive deps
            'b2': {'a2': 2, 'c2': 2, 'directory': 0}}  # includes all transitive deps
    }

    # b1 and b2 use most recent runs with all dependencies included
    result = rv.get_deps(['b1', 'b2'], deps_map)
    expected = {'b1': 2, 'b2': 2, 'a1': 2, 'a2': 2, 'c1': 2, 'c2': 2, 'directory': 0}
    assert result == expected

def test_get_deps_shared_dependency_different_levels():
    """Test parameters that share some dependencies but not all."""
    deps_map = {
        0: {'directory': {}},
        1: {'shared': {'directory': 0},
            'unique1': {'directory': 0},
            'unique2': {'directory': 0},
            'b1': {'shared': 1, 'unique1': 1, 'directory': 0},
            'b2': {'shared': 1, 'unique2': 1, 'directory': 0}},
        2: {'shared': {'directory': 0},
            'unique1': {'directory': 0},
            'unique2': {'directory': 0},
            'b1': {'shared': 2, 'unique1': 2, 'directory': 0},
            'b2': {'shared': 2, 'unique2': 2, 'directory': 0}}
    }
    
    # b1 and b2 both depend on shared but have different unique deps
    result = rv.get_deps(['b1', 'b2'], deps_map)
    # Should be at same run since they share 'shared' dependency
    expected = {'b1': 2, 'b2': 2, 'shared': 2, 'unique1': 2, 'unique2': 2, 'directory': 0}
    assert result == expected

def test_get_deps_all_transitive_deps_included():
    """Test that all transitive dependencies are included from deps_map."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'a1': 1, 'b1': 1, 'directory': 0}},  # c1 includes all transitive deps
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0},
            'c1': {'b1': 2, 'a1': 2, 'directory': 0}}  # c1 includes a1 transitively from b1
    }

    # c1:2 depends on b1:2 and transitively on a1:2 (all in deps_map)
    result = rv.get_deps(['c1'], deps_map)
    expected = {'c1': 2, 'b1': 2, 'a1': 2, 'directory': 0}
    assert result == expected
deps_map0 = {0: {"param1": {}}}
deps_map1 = {0: {"param1": {}, "param2": {}}, 1: {"param1": {'param2': 0}}}
@pytest.mark.parametrize("param_names,deps_map,expected", [
    (["param1"], deps_map0, {"param1": 0}),
    (["param1"], deps_map1, {"param1": 1, "param2": 0}),
    (["param2"], deps_map1, {"param2": 0})
])
def test_get_deps(param_names, deps_map, expected):
    result = rv.get_deps(param_names, deps_map)
    assert result == expected

def test_get_deps_empty_param_names():
    assert rv.get_deps([], {}) == {}

# Testing variety of function run orders for the following function deps
#      B -> C 
# A ->         -> F
#      D -> E 
# Here the parameter and return names are 
# A = (['directory'], ['a1', 'a2'])
# B = (['a1'], ['b1'])
# C = (['a2', 'b1'], ['c1', 'c2'])
# D = (['a2'], ['d1', 'd2'])
# E = (['d2'], ['e1'])
# F = (['e1', 'c2'], ['f1']) 
# Test function names describe function run order that produces deps_map 

def test_get_deps_ABC():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
             'a2': {'directory': 0},
             'b1': {'a1': 1, 'directory': 0},
             'c1': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
             'c2': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1}}}
    with pytest.raises(ValueError):
        rv.get_deps(['f1'], deps_map)
    
    expected = {'c1': 1, 'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1} 
    assert rv.get_deps(['c1'], deps_map) == expected

def test_get_deps_ABCDEABC():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
              'a2': {'directory': 0},
              'b1': {'a1': 1, 'directory': 0},
              'c1': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
              'c2': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
              'd1': {'a2': 1, 'directory': 0},
              'd2': {'a2': 1, 'directory': 0},
              'e1': {'d2': 1, 'a2': 1, 'directory': 0}},
             2: {'a1': {'directory': 0},
              'a2': {'directory': 0},
              'b1': {'a1': 2, 'directory': 0},
              'c1': {'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2},
              'c2': {'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2}}}
    
    expected = {'c1': 2, 'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2} 
    assert rv.get_deps(['c1'], deps_map) == expected

    expected = {'a1': 2, 'directory': 0} 
    assert rv.get_deps(['a1'], deps_map) == expected 

    with pytest.raises(ValueError):
        rv.get_deps(['f1'], deps_map)

    # Raises warning when backtracking 
    with pytest.warns(UserWarning):
        expected = {'e1': 1, 'c1': 1, 'd2': 1, 'a2': 1, 
                    'directory': 0, 'b1': 1, 'a1': 1}
        assert rv.get_deps(['e1', 'c1'], deps_map) == expected 

def test_get_deps_AAAABB():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 4, 'directory': 0}},
             2: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 4, 'directory': 0}},
             3: {'a1': {'directory': 0}, 'a2': {'directory': 0}},
             4: {'a1': {'directory': 0}, 'a2': {'directory': 0}}}
    
    expected = {'a1': 4, 'a2': 4, 'directory': 0}
    assert rv.get_deps(['a1', 'a2'], deps_map) == expected

    with pytest.raises(ValueError): 
        rv.get_deps(['b2'], deps_map)

    expected = {'b1': 2, 'a1': 4, 'directory': 0} 
    assert rv.get_deps(['b1'], deps_map) == expected

def test_get_deps_multi_param_no_conflict():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0},
                 'd1': {'a2': 1, 'directory': 0}}}
    expected = {'b1': 1, 'd1': 1, 'a1': 1, 'a2': 1, 'directory': 0}
    assert rv.get_deps(['b1', 'd1'], deps_map) == expected

def test_get_deps_input_depends_on_input_same_run():
    # Test case where one input parameter depends on another at same run
    # Function A outputs a1, Function B takes [a1] and outputs b1
    # Request [a1, b1] where b1 depends on a1, both at run 1
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0}}}
    expected = {'a1': 1, 'b1': 1, 'directory': 0}
    result = rv.get_deps(['a1', 'b1'], deps_map)
    assert result == expected

def test_get_deps_input_depends_on_input_different_runs():
    # Test case where one input parameter depends on another at different run
    # a1 is at run 2, but b1 at run 2 depends on a1 at run 1
    # Should backtrack a1 to run 1, b1 can stay at run 2 (prefer later policy)
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0}},
             2: {'a1': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0}}}

    with pytest.warns(UserWarning):
        expected = {'a1': 1, 'b1': 2, 'directory': 0}
        result = rv.get_deps(['a1', 'b1'], deps_map)
        assert result == expected

def test_get_deps_input_in_subdeps_no_backtrack():
    # Test case where an input parameter also appears in subdeps
    # but at the same run - no backtracking needed
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 1, 'a2': 1, 'directory': 0}}}
    expected = {'a1': 1, 'b1': 1, 'a2': 1, 'directory': 0}
    result = rv.get_deps(['a1', 'b1'], deps_map)
    assert result == expected

def test_get_deps_overlap_inputs_with_subdeps():
    # Requesting both an input ('directory') and a param that depends on it
    # This is now valid - directory should remain, a1 should not be overwritten
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0}}}
    expected = {'directory': 0, 'a1': 1}
    assert rv.get_deps(['directory', 'a1'], deps_map) == expected

def test_get_deps_two_inputs_conflicting_subdeps():
    # Two input parameters with conflicting sub-dependencies
    # e1 depends on a2:1, c1 depends on a2:2 - should backtrack c1 to run 1
    deps_map = {0: {'directory': {}},
             1: {'a2': {'directory': 0},
                 'e1': {'a2': 1, 'directory': 0},
                 'c1': {'a2': 1, 'directory': 0}},
             2: {'a2': {'directory': 0},
                 'c1': {'a2': 2, 'directory': 0}}}
    
    with pytest.warns(UserWarning):
        expected = {'e1': 1, 'c1': 1, 'a2': 1, 'directory': 0}
        result = rv.get_deps(['e1', 'c1'], deps_map)
        assert result == expected


@pytest.mark.parametrize("param_names,deps_map", [
    (123, {}),  # param_names not a list or np.ndarray
    (["param1"], "not a dict"),  # deps_map not a dict
    (["param1", 123], {})  # param_names contains non-string
])
def test_get_deps_invalid_input(param_names, deps_map):
    with pytest.raises(ValueError):
        rv.get_deps(param_names, deps_map)

################################################################################
########################### enforced_max_runs tests ############################
################################################################################
def test_get_deps_enforced_max_runs_basic():
    """Test enforcing a maximum run for a single parameter."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}},
        2: {'a1': {'directory': 0}},
        3: {'a1': {'directory': 0}}
    }
    
    # Without enforcement, would use run 3
    result_default = rv.get_deps(['a1'], deps_map)
    assert result_default == {'a1': 3, 'directory': 0}
    
    # With enforcement at run 2, should use run 2
    result_enforced = rv.get_deps(['a1'], deps_map, enforced_max_runs={'a1': 2})
    assert result_enforced == {'a1': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_allows_backtracking():
    """Test that enforced parameters can still be backtracked if conflicts require it."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},  # b1:2 still depends on a1:1
        3: {'a1': {'directory': 0}}  # a1:3 exists but b1 doesn't
    }
    
    # Enforce a1 at max run 3, but b1 at run 2 requires a1:1
    # Should backtrack a1 from 3 to 1 to resolve conflict
    with pytest.warns(UserWarning):
        result = rv.get_deps(['a1', 'b1'], deps_map, enforced_max_runs={'a1': 3})
        assert result == {'a1': 1, 'b1': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_multiple_params():
    """Test enforcing maximum runs for multiple parameters."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'a2': {'directory': 0}},
        2: {'a1': {'directory': 0},
            'a2': {'directory': 0}},
        3: {'a1': {'directory': 0},
            'a2': {'directory': 0}}
    }
    
    # Enforce different max runs for different parameters
    result = rv.get_deps(
        ['a1', 'a2'], 
        deps_map, 
        enforced_max_runs={'a1': 1, 'a2': 2}
    )
    assert result == {'a1': 1, 'a2': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_with_dependencies():
    """Test enforcing max run on a parameter that has dependencies."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'a1': 3, 'directory': 0}}
    }
    
    # Enforce b1 at max run 2, should use b1:2 and a1:2
    result = rv.get_deps(['b1'], deps_map, enforced_max_runs={'b1': 2})
    assert result == {'b1': 2, 'a1': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_subdependency():
    """Test enforcing max run on a subdependency (not in param_names)."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'a1': 3, 'directory': 0}}
    }
    
    # Enforce a1 at max run 2, even though b1 would prefer run 3
    # Should backtrack b1 to find version that uses a1:2 or earlier
    with pytest.warns(UserWarning):
        result = rv.get_deps(['b1'], deps_map, enforced_max_runs={'a1': 2})
        assert result == {'b1': 2, 'a1': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_mixed_enforced_and_free():
    """Test mix of enforced and non-enforced parameters."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'a2': {'directory': 0},
            'b1': {'a1': 1, 'a2': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'a2': {'directory': 0},
            'b1': {'a1': 2, 'a2': 2, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'a2': {'directory': 0},
            'b1': {'a1': 3, 'a2': 3, 'directory': 0}}
    }
    
    # Enforce a1 at run 1, let a2 use most recent (3)
    # Should backtrack to find consistent versions
    with pytest.warns(UserWarning):
        result = rv.get_deps(['a1', 'a2', 'b1'], deps_map, enforced_max_runs={'a1': 1})
        # All should backtrack to run 1 to be consistent with a1:1
        assert result == {'a1': 1, 'a2': 1, 'b1': 1, 'directory': 0}


def test_get_deps_enforced_max_runs_exceeds_available():
    """Test error when enforced run exceeds available runs."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}},
        2: {'a1': {'directory': 0}}
    }
    
    # Try to enforce a1 at run 5, but only runs 0-2 exist
    with pytest.raises(ValueError, match="exceeds most recent available"):
        rv.get_deps(['a1'], deps_map, enforced_max_runs={'a1': 5})


def test_get_deps_enforced_max_runs_parameter_not_in_deps_map():
    """Test enforcing run for parameter that doesn't exist in deps_map."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}}
    }
    
    # Enforce run for 'b1' which doesn't exist - should fail during dependency lookup
    with pytest.raises(ValueError):
        rv.get_deps(['b1'], deps_map, enforced_max_runs={'b1': 1})


def test_get_deps_enforced_max_runs_at_earliest_run():
    """Test enforcing a parameter at its earliest available run."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}},
        2: {'a1': {'directory': 0}},
        3: {'a1': {'directory': 0}}
    }
    
    # Enforce at run 1 (earliest non-directory run)
    result = rv.get_deps(['a1'], deps_map, enforced_max_runs={'a1': 1})
    assert result == {'a1': 1, 'directory': 0}


def test_get_deps_enforced_max_runs_complex_cascade():
    """Test enforcing in a complex dependency cascade."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'b1': 1, 'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0},
            'c1': {'b1': 2, 'a1': 2, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'a1': 3, 'directory': 0},
            'c1': {'b1': 3, 'a1': 3, 'directory': 0}}
    }
    
    # Enforce b1 at max run 2, requesting c1
    # c1 at run 3 depends on b1:3, but b1 is capped at 2
    # Should backtrack c1 to run 2
    with pytest.warns(UserWarning):
        result = rv.get_deps(['c1'], deps_map, enforced_max_runs={'b1': 2})
        assert result == {'c1': 2, 'b1': 2, 'a1': 2, 'directory': 0}


def test_get_deps_enforced_max_runs_invalid_type():
    """Test that invalid enforced_max_runs type raises error."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}}
    }
    
    with pytest.raises(ValueError, match="enforced_max_runs must be a dictionary"):
        rv.get_deps(['a1'], deps_map, enforced_max_runs="not_a_dict")


def test_get_deps_enforced_max_runs_empty_dict():
    """Test that empty enforced_max_runs dict works (no enforcement)."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0}},
        2: {'a1': {'directory': 0}}
    }
    
    # Empty dict should behave like no enforcement
    result = rv.get_deps(['a1'], deps_map, enforced_max_runs={})
    assert result == {'a1': 2, 'directory': 0}

################################################################################
############################## _detect_conflicts ###############################
################################################################################

def test_detect_conflicts_no_conflicts():
    """Test _detect_conflicts returns empty list when no conflicts exist."""
    sub_deps = {
        'param1': {'a1': 2, 'b1': 3, 'directory': 0},
        'param2': {'a1': 2, 'c1': 4, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    assert result == []

def test_detect_conflicts_single_conflict():
    """Test _detect_conflicts identifies single conflicting parameter."""
    sub_deps = {
        'param1': {'a1': 2, 'b1': 3, 'directory': 0},
        'param2': {'a1': 1, 'c1': 4, 'directory': 0}  # a1 differs
    }
    result = rv._detect_conflicts(sub_deps)
    # Should identify param1 (has higher a1 value)
    assert 'param1' in result

def test_detect_conflicts_multiple_params_multiple_conflicts():
    """Test _detect_conflicts with multiple conflicting dependencies."""
    sub_deps = {
        'param1': {'a1': 3, 'b1': 2, 'directory': 0},
        'param2': {'a1': 1, 'b1': 4, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    # Both params have conflicts (a1 and b1 differ)
    assert len(result) > 0
    assert any(p in result for p in ['param1', 'param2'])

def test_detect_conflicts_three_way_conflict():
    """Test _detect_conflicts with three parameters having conflicts."""
    sub_deps = {
        'param1': {'shared': 3, 'directory': 0},
        'param2': {'shared': 1, 'directory': 0},
        'param3': {'shared': 2, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    # Should detect conflicts among params
    assert len(result) > 0

def test_detect_conflicts_empty_subdeps():
    """Test _detect_conflicts with empty sub_deps."""
    sub_deps = {}
    result = rv._detect_conflicts(sub_deps)
    assert result == []

def test_detect_conflicts_single_param_no_conflict():
    """Test _detect_conflicts with single parameter (no conflict possible)."""
    sub_deps = {
        'param1': {'a1': 2, 'b1': 3, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    assert result == []

def test_detect_conflicts_identifies_higher_run():
    """Test that param with higher run value is identified for backtracking."""
    sub_deps = {
        'param_low': {'shared': 1, 'directory': 0},
        'param_high': {'shared': 5, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    # param_high should be in the list (has the higher value)
    assert 'param_high' in result

def test_detect_conflicts_complex_cascade():
    """Test _detect_conflicts in complex multi-level scenario."""
    sub_deps = {
        'c1': {'a1': 2, 'b1': 2, 'directory': 0, 'c1': 2},
        'b1': {'a1': 2, 'b1': 2, 'directory': 0},
        'a1': {'a1': 2, 'directory': 0}
    }
    result = rv._detect_conflicts(sub_deps)
    # No conflicts - all agree on run versions
    assert result == []

################################################################################
######################## _find_best_deps_recursive #############################
################################################################################

def test_find_best_deps_recursive_no_conflicts():
    """Test recursive function returns immediately when no conflicts."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}}
    }
    current_deps = {'a1': 1, 'b1': 1}
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['a1', 'b1'], {})
    
    assert result is not None
    all_deps, run_sum, backtracked = result
    assert all_deps == {'a1': 1, 'b1': 1, 'directory': 0}
    assert run_sum == 2  # 1 + 1 + 0
    assert backtracked == {}

def test_find_best_deps_recursive_optimizes_run_sum():
    """Test that recursive function chooses path with highest run_sum."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'a1': 1, 'b1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0},
            'c1': {'a1': 1, 'b1': 1, 'directory': 0}}  # c1:2 would conflict
    }
    
    # Start with c1:1, b1:2 - b1 depends on a1:2, but c1:1 depends on a1:1
    # Should backtrack to b1:1 for compatibility and highest run_sum
    current_deps = {'c1': 1, 'b1': 2}
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['c1', 'b1'], {})
    
    assert result is not None
    all_deps, run_sum, backtracked = result
    # Should have backtracked to b1:1 for consistency
    assert all_deps['b1'] == 1
    assert 'b1' in backtracked

def test_find_best_deps_recursive_enforced_max_runs():
    """Test that recursive function respects enforced_max_runs."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'a1': 3, 'directory': 0}}
    }
    
    # When both params in current_deps, enforced_max_runs is checked
    current_deps = {'b1': 2, 'a1': 2}
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['b1'], {'a1': 2})
    
    assert result is not None
    all_deps, run_sum, backtracked = result
    assert all_deps['a1'] <= 2  # Must respect enforced max
    assert all_deps['b1'] == 2  # Compatible with a1:2

def test_find_best_deps_recursive_no_valid_solution():
    """Test recursive function returns None when no resolution possible."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0}}  # b1:1 needs a1:2
        # No a1 at run 2, and b1 has no other versions
    }
    
    # Start with b1:1, which needs a1:2 that doesn't exist
    # Even if we backtrack b1, there are no earlier versions
    current_deps = {'b1': 1}
    # Enforce a1 cannot exceed run 1 (but we need a1:2)
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['b1'], {'a1': 1})
    
    # Should return None: b1:1 needs a1:2 but enforced max is a1:1
    assert result is None

def test_find_best_deps_recursive_memoization():
    """Test that memoization cache is used to avoid redundant computation."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0},
            'c1': {'a1': 1, 'directory': 0}}
    }
    
    current_deps = {'a1': 1, 'b1': 1, 'c1': 1}
    memo = {}
    
    # First call populates memo
    result1 = rv._find_best_deps_recursive(current_deps, deps_map, ['a1', 'b1', 'c1'], {}, memo)
    
    # Second call with same state should use memoized result
    result2 = rv._find_best_deps_recursive(current_deps, deps_map, ['a1', 'b1', 'c1'], {}, memo)
    
    assert result1 is result2  # Should be the exact same object from cache
    assert len(memo) > 0  # Memo should have entries

def test_find_best_deps_recursive_multiple_backtrack_paths():
    """Test that function explores multiple backtracking paths and picks best."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'directory': 0},
            'c1': {'a1': 1, 'b1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'directory': 0},
            'c1': {'a1': 2, 'b1': 1, 'directory': 0}},
        3: {'a1': {'directory': 0},
            'b1': {'directory': 0},
            'c1': {'a1': 1, 'b1': 3, 'directory': 0}}
    }
    
    # Start with a1:2, b1:3 - conflicts because c1 versions don't match these
    current_deps = {'a1': 2, 'b1': 3, 'c1': 2}
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['a1', 'b1', 'c1'], {})
    
    assert result is not None
    all_deps, run_sum, backtracked = result
    # Should find a valid combination
    assert len(backtracked) > 0  # Something was backtracked

def test_find_best_deps_recursive_prefers_higher_runs():
    """Test that when multiple solutions exist, higher run_sum is chosen."""
    deps_map = {
        0: {'directory': {}},
        1: {'a1': {'directory': 0},
            'b1': {'a1': 1, 'directory': 0}},
        2: {'a1': {'directory': 0},
            'b1': {'a1': 2, 'directory': 0}}
    }
    
    # Both b1:1 and b1:2 would work, should prefer b1:2 (higher run_sum)
    current_deps = {'b1': 2}
    result = rv._find_best_deps_recursive(current_deps, deps_map, ['b1'], {})
    
    assert result is not None
    all_deps, run_sum, backtracked = result
    assert all_deps['b1'] == 2  # Should use higher run
    assert backtracked == {}  # No backtracking needed