import pytest 
import citkid.pipeline.run_validation as rv 

# For all of this, I am not testing the structure of the saved dict. 
# I am assuming that it is produced by other parts of the code correctly.

################################################################################
############################### _get_most_recent_run ###########################
################################################################################
@pytest.mark.parametrize("name,saved,expected", [
    # Basic case: parameter exists in multiple runs
    ("param1", {0: [("param1", {}), ("param2", {})],
                1: [("param3", {})],
                2: [("param1", {}), ("param4", {})]}, 2),
    # Parameter exists only in one run
    ("param2", {0: [("param1", {})],
                1: [("param2", {})]}, 1),
    # Parameter does not exist in any run
    ("paramX", {0: [("param1", {})],
                1: [("param2", {})]}, -1),
    # Empty saved dictionary
    ("param1", {}, -1),
    # skipped runs
    ("param1", {0: [("param2", {})],
                2: [("param1", {})]}, 2),
])
def test_get_most_recent_run(name, saved, expected):
    result = rv._get_most_recent_run(name, saved)
    assert result == expected


@pytest.mark.parametrize("name,saved", [
    (123, {0: [("param1", {})]}),  # name is not a string
    ("param1", [("param1", {})]),   # saved is not a dict   
])
def test_get_most_recent_run_invalid_inputs(name, saved):
    with pytest.raises(ValueError):
        rv._get_most_recent_run(name, saved)


################################################################################
############################### _get_sub_dependencies ##########################
################################################################################
@pytest.mark.parametrize("name,run_idx,saved,expected", [
    # Basic case: parameter exists with dependencies
    ("param1", 2, {2: [("param1", {"param2": 1, "param3": 0})]}, 
                   {"param2": 1, "param3": 0}),
    # Parameter exists with no dependencies
    ("param2", 1, {1: [("param2", {})]}, {}),
    # Parameter does not exist in the specified run
    ("paramX", 0, {0: [("param1", {})]}, LookupError),
    # Multiple entries for the same parameter in the run
    ("param1", 2, {2: [("param1", {}), ("param1", {"param2": 1})]}, 
                   ValueError),
    # Empty dependencies
    ("param3", 3, {3: [("param3", {})]}, {}),
    # skipped runs
    ("param1", 2, {0: [("param1", {})],
                   2: [("param2", {})]}, LookupError),
    # Parameter exists in earlier run but not in specified run
    ("param1", 1, {0: [("param1", {})], 
                   1: [("param2", {})]}, LookupError),
])
def test_get_sub_dependencies(name, run_idx, saved, expected):
    if expected is LookupError:
        with pytest.raises(LookupError):
            rv._get_sub_dependencies(name, run_idx, saved)
    elif expected is ValueError:
        with pytest.raises(ValueError):
            rv._get_sub_dependencies(name, run_idx, saved)
    else:
        result = rv._get_sub_dependencies(name, run_idx, saved)
        assert result == expected


@pytest.mark.parametrize("name,run_idx,saved", [
    (123, 0, {0: [("param1", {})]}),  # name is not a string
    ("param1", "0", {0: [("param1", {})]}),  # run_idx is not an integer
    ("param1", 0, [("param1", {})]),   # saved is not a dict   
])
def test_get_sub_dependencies_invalid_inputs(name, run_idx, saved):
    with pytest.raises(ValueError):
        rv._get_sub_dependencies(name, run_idx, saved)

################################################################################
############################### _get_lowest_runs ###############################
################################################################################
# Not validating structure of sub_dependencies beyond being a dict, because 
# it is generated by _get_sub_dependencies which is already tested.
@pytest.mark.parametrize("sub_dependencies,sd_exp,conflicts_exp", [
    # Basic case: multiple parameters with different runs
    ({"param1": {"paramA": 2, "paramB": 3},
      "param2": {"paramA": 1, "paramC": 4}}, 
     {"paramA": 1, "paramB": 3, "paramC": 4}, True),
    # Single parameter with single dependency
    ({"param1": {"paramA": 5}}, 
     {"paramA": 5}, False),
    # Multiple parameters with overlapping dependencies
    ({"param1": {"paramA": 3, "paramB": 2},
      "param2": {"paramA": 1, "paramB": 4}}, 
     {"paramA": 1, "paramB": 2}, True),
    # Empty sub_dependencies
    ({}, {}, False),
    # Parameters with no dependencies
    ({"param1": {}, "param2": {}}, {}, False),
])
def test_get_lowest_runs(sub_dependencies, sd_exp, conflicts_exp):
    result, conflicts = rv._get_lowest_runs(sub_dependencies)
    assert result == sd_exp
    assert conflicts == conflicts_exp

@pytest.mark.parametrize("sub_dependencies", [
    ["param1", {"paramA": 2}],  # sub_dependencies is not a dict
])
def test_get_lowest_runs_invalid_inputs(sub_dependencies):
    with pytest.raises(ValueError):
        rv._get_lowest_runs(sub_dependencies)

################################################################################
############################## _get_dependencies ###############################
################################################################################
# Need to test linear and nonlinear paths, with many combinations of conflicts.
# This is more complex and may require more extensive test cases. 
def test_get_dependencies_temp():
    raise NotImplementedError("Tests for _get_dependencies not yet implemented")