import pytest 
import citkid.pipeline.dependencies as rv 

# For all of this, I am not testing the structure of the saved dict. 
# I am assuming that it is produced by other parts of the code correctly.

################################################################################
############################### _get_most_recent_run ###########################
################################################################################
@pytest.mark.parametrize("name,deps_map,expected", [
    # Basic case: parameter exists in multiple runs
    ("param1", {0: {"param1": {}, "param2": {}},
                1: {"param3": {}},
                2: {"param1": {}, "param4": {}}}, 2),
    # Parameter exists only in one run
    ("param2", {0: {"param1": {}},
                1: {"param2": {}}}, 1),
    # Parameter does not exist in any run
    ("paramX", {0: {"param1": {}},
                1: {"param2": {}}}, -1),
    # Empty deps_map dictionary
    ("param1", {}, -1),
    # skipped runs
    ("param1", {0: {"param2": {}},
                2: {"param1": {}}}, 2),
])
def test_get_most_recent_run(name, deps_map, expected):
    result = rv.get_most_recent_run(name, deps_map)
    assert result == expected


@pytest.mark.parametrize("name,deps_map", [
    (123, {0: {"param1": {}}}),  # name is not a string
    ("param1", [("param1", {})]),   # deps_map is not a dict   
])
def test_get_most_recent_run_invalid_inputs(name, deps_map):
    with pytest.raises(ValueError):
        rv.get_most_recent_run(name, deps_map)

def test_get_most_recent_run_ignores_non_dict_run_entries():
    # Run 0 is a non-dict (legacy/invalid), run 1 is proper dict
    deps_map = {0: [("param1", {})], 1: {"param1": {}}}
    assert rv.get_most_recent_run("param1", deps_map) == 1

################################################################################
################################# _get_sub_deps ################################
################################################################################
@pytest.mark.parametrize("name,run_idx,deps_map,expected", [
    # Basic case: parameter exists with deps
    ("param1", 2, {2: {"param1": {"param2": 1, "param3": 0}}}, 
                   {"param2": 1, "param3": 0}),
    # Parameter exists with no deps
    ("param2", 1, {1: {"param2": {}}}, {}),
    # Parameter does not exist in the specified run
    ("paramX", 0, {0: {"param1": {}}}, LookupError),
    # Invalid deps type for a parameter
    ("param1", 2, {2: {"param1": []}}, 
                   ValueError),
    # Empty deps
    ("param3", 3, {3: {"param3": {}}}, {}),
    # skipped runs
    ("param1", 2, {0: {"param1": {}},
                   2: {"param2": {}}}, LookupError),
    # Parameter exists in earlier run but not in specified run
    ("param1", 1, {0: {"param1": {}}, 
                   1: {"param2": {}}}, LookupError),
])
def test_get_sub_deps(name, run_idx, deps_map, expected):
    if expected is LookupError:
        with pytest.raises(LookupError):
            rv._get_sub_deps(name, run_idx, deps_map)
    elif expected is ValueError:
        with pytest.raises(ValueError):
            rv._get_sub_deps(name, run_idx, deps_map)
    else:
        result = rv._get_sub_deps(name, run_idx, deps_map)
        assert result == expected


@pytest.mark.parametrize("name,run_idx,deps_map", [
    (123, 0, {0: {"param1": {}}}),  # name is not a string
    ("param1", "0", {0: {"param1": {}}}),  # run_idx is not an integer
    ("param1", 0, [("param1", {})]),   # deps_map is not a dict   
])
def test_get_sub_deps_invalid_inputs(name, run_idx, deps_map):
    with pytest.raises(ValueError):
        rv._get_sub_deps(name, run_idx, deps_map)

def test_get_sub_deps_missing_run():
    deps_map = {0: {"param1": {}}}
    with pytest.raises(LookupError):
        rv._get_sub_deps("param1", 1, deps_map)

################################################################################
############################### _get_lowest_runs ###############################
################################################################################
# Not validating structure of sub_deps beyond being a dict, because 
# it is generated by _get_sub_deps which is already tested.
@pytest.mark.parametrize("sub_deps,sd_exp,conflicts_exp", [
    # Basic case: multiple parameters with different runs
    ({"param1": {"paramA": 2, "paramB": 3},
      "param2": {"paramA": 1, "paramC": 4}}, 
     {"paramA": 1, "paramB": 3, "paramC": 4}, True),
    # Single parameter with single dependency
    ({"param1": {"paramA": 5}}, 
     {"paramA": 5}, False),
    # Multiple parameters with overlapping deps
    ({"param1": {"paramA": 3, "paramB": 2},
      "param2": {"paramA": 1, "paramB": 4}}, 
     {"paramA": 1, "paramB": 2}, True),
    # Empty sub_deps
    ({}, {}, False),
    # Parameters with no deps
    ({"param1": {}, "param2": {}}, {}, False),
])
def test_get_lowest_runs(sub_deps, sd_exp, conflicts_exp):
    result, conflicts = rv._get_lowest_runs(sub_deps)
    assert result == sd_exp
    assert conflicts == conflicts_exp

@pytest.mark.parametrize("sub_deps", [
    ["param1", {"paramA": 2}],  # sub_deps is not a dict
])
def test_get_lowest_runs_invalid_inputs(sub_deps):
    with pytest.raises(ValueError):
        rv._get_lowest_runs(sub_deps)

def test_get_lowest_runs_invalid_subdep_value():
    with pytest.raises(ValueError):
        rv._get_lowest_runs({"param1": [1, 2]})

################################################################################
################################### get_deps ###################################
################################################################################
deps_map0 = {0: {"param1": {}}}
deps_map1 = {0: {"param1": {}, "param2": {}}, 1: {"param1": {'param2': 0}}}
@pytest.mark.parametrize("param_names,deps_map,expected", [
    (["param1"], deps_map0, {"param1": 0}),
    (["param1"], deps_map1, {"param1": 1, "param2": 0}),
    (["param2"], deps_map1, {"param2": 0})
])
def test_get_deps(param_names, deps_map, expected):
    result = rv.get_deps(param_names, deps_map)
    assert result == expected

def test_get_deps_empty_param_names():
    assert rv.get_deps([], {}) == {}

# Testing variety of function run orders for the following function deps
#      B -> C 
# A ->         -> F
#      D -> E 
# Here the parameter and return names are 
# A = (['directory'], ['a1', 'a2'])
# B = (['a1'], ['b1'])
# C = (['a2', 'b1'], ['c1', 'c2'])
# D = (['a2'], ['d1', 'd2'])
# E = (['d2'], ['e1'])
# F = (['e1', 'c2'], ['f1']) 
# Test function names describe function run order that produces deps_map 

def test_get_deps_ABC():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
             'a2': {'directory': 0},
             'b1': {'a1': 1, 'directory': 0},
             'c1': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
             'c2': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1}}}
    with pytest.raises(ValueError):
        rv.get_deps(['f1'], deps_map)
    
    expected = {'c1': 1, 'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1} 
    assert rv.get_deps(['c1'], deps_map) == expected

def test_get_deps_ABCDEABC():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
              'a2': {'directory': 0},
              'b1': {'a1': 1, 'directory': 0},
              'c1': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
              'c2': {'a2': 1, 'b1': 1, 'directory': 0, 'a1': 1},
              'd1': {'a2': 1, 'directory': 0},
              'd2': {'a2': 1, 'directory': 0},
              'e1': {'d2': 1, 'a2': 1, 'directory': 0}},
             2: {'a1': {'directory': 0},
              'a2': {'directory': 0},
              'b1': {'a1': 2, 'directory': 0},
              'c1': {'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2},
              'c2': {'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2}}}
    
    expected = {'c1': 2, 'a2': 2, 'b1': 2, 'directory': 0, 'a1': 2} 
    assert rv.get_deps(['c1'], deps_map) == expected

    expected = {'a1': 2, 'directory': 0} 
    assert rv.get_deps(['a1'], deps_map) == expected 

    with pytest.raises(ValueError):
        rv.get_deps(['f1'], deps_map)

    # Raises warning when backtracking 
    with pytest.warns(UserWarning):
        expected = {'e1': 1, 'c1': 1, 'd2': 1, 'a2': 1, 
                    'directory': 0, 'b1': 1, 'a1': 1}
        assert rv.get_deps(['e1', 'c1'], deps_map) == expected 

def test_get_deps_AAAABB():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 4, 'directory': 0}},
             2: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 4, 'directory': 0}},
             3: {'a1': {'directory': 0}, 'a2': {'directory': 0}},
             4: {'a1': {'directory': 0}, 'a2': {'directory': 0}}}
    
    expected = {'a1': 4, 'a2': 4, 'directory': 0}
    assert rv.get_deps(['a1', 'a2'], deps_map) == expected

    with pytest.raises(ValueError): 
        rv.get_deps(['b2'], deps_map)

    expected = {'b1': 2, 'a1': 4, 'directory': 0} 
    assert rv.get_deps(['b1'], deps_map) == expected

def test_get_deps_overlap_inputs_with_subdeps_error():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0}}}
    # Requesting both an input ('directory') and a param that depends on it
    with pytest.raises(ValueError):
        rv.get_deps(['directory', 'a1'], deps_map)

def test_get_deps_multi_param_no_conflict():
    deps_map = {0: {'directory': {}},
             1: {'a1': {'directory': 0},
                 'a2': {'directory': 0},
                 'b1': {'a1': 1, 'directory': 0},
                 'd1': {'a2': 1, 'directory': 0}}}
    expected = {'b1': 1, 'd1': 1, 'a1': 1, 'a2': 1, 'directory': 0}
    assert rv.get_deps(['b1', 'd1'], deps_map) == expected


@pytest.mark.parametrize("param_names,deps_map", [
    (123, {}),  # param_names not a list or np.ndarray
    (["param1"], "not a dict"),  # deps_map not a dict
    (["param1", 123], {})  # param_names contains non-string
])
def test_get_deps_invalid_input(param_names, deps_map):
    with pytest.raises(ValueError):
        rv.get_deps(param_names, deps_map)